# Generated by Django 6.1.1 on 2026-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_smstnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstnewsletter',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
