# Generated by Django 6.1.1 on 2026-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_smstnewsletter_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstuser',
            name='username',
            field=models.CharField(default='smst', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
