# Generated by Django 6.1.1 on 2026-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_smstuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstuser',
            name='social_acc',
            field=models.BooleanField(default=True),
        ),
    ]
