name: Smst Code Quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-versions: 22
          cache: npm
        
      - name: Install dependencies
        run: npm ci
      
      - name: Check formatting
        run: npm run format-check
      
      - name: lint
        run: npm run lint
      
      - name: Check commit messages
        if: github.event_name == 'pull_request'
        run: npx commitlint --from "${{ github.event.pull_request.base.sha }}" --to "${{ github.event.pull_request.head.sha }}"
      
      - name: setup Python3 environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: venv/bin/pip install -r requirements.txt

      - name: Run Tests
        env:  
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_SECRET_KEY: ${{ secrets.CLOUDINARY_SECRET_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GOOGLE_SECRET_KEY: ${{ secrets.GOOGLE_SECRET_KEY }}
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
        run: venv/bin/python manage.py test test.test_models 